all: list listSol fib fib1

fib: fib.c
	gcc -Wall -Werror -o fib fib.c

fib1: fib1.c
	gcc -Wall -Werror -o fib1 fib1.c

list: list.c
	gcc -Wall -Werror -o list list.c

listSol: listSol.c
	gcc -Wall -Werror -o listSol listSol.c
